# Generated by Django 5.0.3 on 2024-05-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.simpleuser'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.organization'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.simpleuser'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.projecttype'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.simpleuser'),
        ),
    ]
