# Generated by Django 5.0.3 on 2024-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpleuser",
            name="firstName",
        ),
        migrations.RemoveField(
            model_name="simpleuser",
            name="lastName",
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
