# Generated by Django 5.0.3 on 2024-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
